# network_mode: "host" does not work on OSX...
# WIP: Does not work at the moment... locks up when it tries to start docker
#   container inside the taskmanager flink task.

version: '2.1'

networks:
  backend:
    name: beam_backend

services:

  jobserver:
    # This is to host the service:
    #   ./gradlew -p runners/flink/1.8/job-server runShadow -P flinkMasterUrl=localhost:8081
    image: ${DOCKER_REGISTRY_URL}/beam/flink-job-server:${BEAM_VERSION}
    command: "--flink-master-url=jobmanager:8081"
    networks:
      - backend
    ports:
      - "8098:8098"  # ArtifactStagingService
      - "8097:8097"  # Java ExpansionService
      - "8099:8099"  # JobService
    volumes:
      - /tmp/beam-artifact-staging:/tmp/beam-artifact-staging

  jobmanager:
    image: ${DOCKER_REGISTRY_URL}/beam/docker-flink:${FLINK_VERSION}
    networks:
      - backend
    ports:
      - "8081:8081"
    expose:
      - "6123"
      - "6124"
      - "6125"
      - "8080-8090"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  taskmanager:
    image: ${DOCKER_REGISTRY_URL}/beam/docker-flink:${FLINK_VERSION}
    depends_on:
      - jobmanager
    networks:
      - backend
    ports:
      - "8100-8200:8100-8200"
    expose:
      - "6121"
      - "6122"
      - "6124"
      - "6125"
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - DOCKER_MAC_CONTAINER=1
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/app/.cred/render-pubsub.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/beam-artifact-staging:/tmp/beam-artifact-staging
      - ~/projects/rillbeam/.cred/render-pubsub.json:/opt/app/.cred/render-pubsub.json
