version: '3.7'

networks:
  back:


services:

# Does not work stand-alone...
# LINUX:
#   docker run --network=host -v `which docker`:/bin/docker -v /var/run/docker.sock:/var/run/docker.sock ${DOCKER_REGISTRY_URL}/beam/flink-job-server:2.13 --job-host=localhost --job-port=8099 --artifact-port=8098 --expansion-port=8097 --flink-master-url=localhost:8081
# OSX:
#   docker run -e DOCKER_MAC_CONTAINER=1 -p 8098:8098 -p 8097:8097 -p 8099:8099 -p 8100-8200:8100-8200 -v `which docker`:/bin/docker -v /var/run/docker.sock:/var/run/docker.sock ${DOCKER_REGISTRY_URL}/beam/flink-job-server:2.13 --job-host=localhost --job-port=8099 --artifact-port=8098 --expansion-port=8097 --flink-master-url=localhost:8081

  jobserver:
    image: ${DOCKER_REGISTRY_URL}/beam/flink-job-server:2.13
    command: "--job-host=localhost --job-port=8099 --artifact-port=8098 --expansion-port=8097 --flink-master-url=jobmanager:8081"
    networks:
      - back
    ports:
      - "8098:8098"  # ArtifactStagingService
      - "8097:8097"  # Java ExpansionService
      - "8099:8099"  # JobService
      - "8100-8200:8100-8200"  # harness_port_range
    volumes:
      - ${DOCKER_BIN:-/usr/bin/docker}:/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      # used to pass artifacts
      - /tmp:/tmp

  jobmanager:
    image: ${DOCKER_REGISTRY_URL}/beam/beam-flink:2.13-1.8
#    depends_on:
#      - jobserver
    networks:
      - back
    expose:
      - "6123"
      - "8081"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  taskmanager:
    image: ${DOCKER_REGISTRY_URL}/beam/beam-flink:2.13-1.8
    depends_on:
      - jobmanager
    networks:
      - back
    expose:
      - "6121"
      - "6122"
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - ${DOCKER_BIN:-/usr/bin/docker}:/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
      # used to pass artifacts
      - /tmp:/tmp
