version: '2.1'

volumes:
  beam-artifacts-staging-volume:

services:

  jobserver:
    # This is to host the service:
    #   ./gradlew :beam-runners-flink-1.8-job-server:runShadow -P flinkMasterUrl=localhost:8081
    image: ${DOCKER_REGISTRY_URL}/beam/flink-job-server:2.13
    command: "--flink-master-url=localhost:8081"
    # need use host networking for the SDK harness container to reach to taskmanager under localhost:<random-port>
    network_mode: "host"
    volumes:
      - beam-artifacts-staging-volume:/tmp/beam-artifact-staging

  jobmanager:
    image: flink:1.8
    # need use host networking for the SDK harness container to reach to taskmanager under localhost:<random-port>
    network_mode: "host"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=localhost

  taskmanager:
    image: ${DOCKER_REGISTRY_URL}/beam/docker-flink:1.8
    depends_on:
      - jobmanager
    # need use host networking for the SDK harness container to reach to taskmanager under localhost:<random-port>
    network_mode: "host"
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=localhost
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - beam-artifacts-staging-volume:/tmp/beam-artifact-staging
